---
- name: all
  hosts: all
  remote_user: root
  become: yes
  gather_facts: yes
  vars:
    username: pg
    brew_formulae:
      - k9s
  roles:
    - common-software
    - docker
    - zsh
    - monolithprojects.homebrew
